#
#  Author: Hari Sekhon
#  Date: 2024-02-27 18:45:11 +0000 (Tue, 27 Feb 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Docs
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                                   I n d e x
# ============================================================================ #

# Check all .md files are referenced in the README.md index

---
name: Index

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.md'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -euxo pipefail {0}

jobs:
  index-check:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'HariSekhon'
    name: Index Check
    timeout-minutes: 3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        #name: Git Checkout  # better to show the action@version

      - name: Check all *.md are in the README.md
        run: |
          exitcode=0
          for x in *.md; do
            [ "$x" = README.md ] && continue
            if ! grep -q "$x" README.md; then
              echo "$x not in README.md"
              exitcode=1
            fi
          done
          exit $exitcode
